### ISSUE TITLE
crr2 tbl_df not working with function? error: Must use vector in `[`... when input is tbl_df

### ISSUE THREAD

**Issue by mljaniczek** [raredd/cmprsk2#2]
When attempting to use `crr2()` function with data in `tbl_df` format (rather than `data.frame`) an error message gets produced due to subsetting error (see reprex below). 

I think this is similar to an issue this other package had: https://github.com/alexpkeil1/qgcomp/issues/1, which they solved in this update (https://github.com/alexpkeil1/qgcomp/commit/84a709ee867adabfa72c9f478c640d75b0a76be5) by adding the argument `drop = TRUE` where the subsetting property "[, ]" was used on class data.frame to produce a vector rather than retain the property of being a data frame. 

When you subset down to one variable using the method `tbl_df[, "variable]` on a tbl_df, it maintains it's status as a tbl_df rather than converting it to a vector (which is the default when using this subsetting method on a data.frame) - see below for example. 

Anyways if you're okay with the change I'm going to submit a pull request to add `drop = TRUE` argument to various places in your code so it can accommodate `tbl_df`! 

``` r
library(cmprsk2)
#> Loading required package: cmprsk
#> Loading required package: survival
library(tibble)

# run model from package example
z1 <- crr2(Surv(futime, event(censored) == death) ~ sex + abo, transplant)
#> Warning in regularize.values(x, y, ties, missing(ties)): collapsing to
#> unique 'x' values

#> Warning in regularize.values(x, y, ties, missing(ties)): collapsing to
#> unique 'x' values

#> Warning in regularize.values(x, y, ties, missing(ties)): collapsing to
#> unique 'x' values
# model runs! 

# make dataset a tibble for demonstration
transplant2 <- as_tibble(transplant)
# now run same model again with tbl_df
z4 <- crr2(Surv(futime, event(censored) == death) ~ sex + abo, transplant2)
#> Must use a vector in `[`, not an object of class matrix.

# Here's the problem: 
str(transplant[, "futime"])
#>  num [1:815] 1197 28 85 231 1271 ...
str(transplant2[, "futime"])
#> Classes 'tbl_df', 'tbl' and 'data.frame':    815 obs. of  1 variable:
#>  $ futime: num  1197 28 85 231 1271 ...

# Whereas in the code when you need to subset this way you can add "drop = TRUE" 
# If you really need it to be a vector! 
str(transplant2[, "futime", drop = TRUE])
#>  num [1:815] 1197 28 85 231 1271 ...
```

<sup>Created on 2019-08-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by raredd** [comment]
Thanks, for the catch--I don't use that package, so it was definitely an oversight. I think this is going to break a lot of code since ``formals(tibble:::`[.tbl_df`)$drop`` is `FALSE` by default, and there are a lot of brackets in this package. For example, `cuminc_pairs(Surv(futime, event(censored) == death) ~ sex + abo, transplant)` will also break for tibbles.

I wonder if the easiest fix would be to coerce the `data` objects to data frames before working on them--have you noticed any problems or loss of data, types, etc by switching back and forth between data frames and tibbles?

Also, that warning is annoying, we'll get that fixed in an update to `cmprsk`

**Comment by mljaniczek** [comment]
@raredd I think it might be unnecessary to coerce the tbl_df to data.frame - it's just a matter of specifying the "drop" within the subsetting technique to be generalizable to both data classes (since data.frame uses `drop = TRUE` by default but tbl_df class uses `drop = FALSE` by default). I'll send over a PR in a minute! Would you want to make a development branch that I can fork so I'm not making modifications right to the master branch? 

By the way, I really admire everything you did with the cmprsk2 package!! Can't wait to use it more!

**Comment by raredd** [comment]
That's great to hear! We were getting tired of fighting the basic interface of the original package, so hopefully this saves you some time and headache.
