### ISSUE TITLE
Interaction terms not working as of 0.0.0.9004

### ISSUE THREAD

**Issue by jquach410** [raredd/cmprsk2#6]
I noticed that the `crr` function is not accepting interaction terms (e.g. `age*sex` or `age:sex`) as of 0.0.0.9004. I reverted to 0.0.0.9003 and it worked again.

Wondering if you knew why this might be happening.

**Comment by raredd** [comment]
sorry about that, bit of an oversight on my part. Should be back to normal now, thanks for catching!

**Comment by jquach410** [comment]
Amazing, thanks!
